import { useEffect, useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import useWallet from 'hooks/useWallet';

import Web3 from 'web3';
import Web3Modal from 'web3modal';

import WalletConnectProvider from '@walletconnect/web3-provider';

const Home: NextPage = () => {
  const [web3Modal, setWeb3Modal] = useState<Web3Modal | null>(null);
  const { wallet, setWallet } = useWallet();

  useEffect(() => {
    const providerOptions = {
      walletconnect: {
        package: WalletConnectProvider, // required
        options: {
          infuraId: process.env.NEXT_PUBLIC_INFURA_PROJECT_ID, // required
        },
      },
    };
    const newWeb3Modal = new Web3Modal({
      network: 'mainnet', // optional
      cacheProvider: true, // optional
      providerOptions, // required
    });
    setWeb3Modal(newWeb3Modal);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <p className="w-full text-left bg-black">hallo</p>
        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="/account" className={styles.card}>
            <h2>Account</h2>
          </a>
          <a href="/jpren.eth" className={styles.card}>
            <h2>Address</h2>
          </a>
        </div>
        <button
          onClick={async () => {
            const provider = await web3Modal?.connect();
            console.log('connected');
            const web3 = new Web3(provider);
            // Subscribe to accounts change
            provider.on('accountsChanged', (accounts: string[]) => {
              console.log(accounts);
            });

            // Subscribe to chainId change
            provider.on('chainChanged', (chainId: number) => {
              console.log(chainId);
            });

            // Subscribe to provider connection
            provider.on('connect', (info: { chainId: number }) => {
              console.log(info);
            });

            // Subscribe to provider disconnection
            provider.on(
              'disconnect',
              (error: { code: number; message: string }) => {
                console.log(error);
              }
            );

            const accounts = await web3.eth.getAccounts();
            const address = accounts[0];
            console.log(address);
            if (address) {
              setWallet({ address });
            }
          }}
        >
          Connect Wallet
        </button>
        <button
          onClick={() => {
            web3Modal?.clearCachedProvider();
          }}
        >
          logout
        </button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
